# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secure_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='secure_message.proto',
  package='serializer',
  syntax='proto2',
  serialized_pb=_b('\n\x14secure_message.proto\x12\nserializer\"-\n\rSecureMessage\x12\x0c\n\x04\x62ody\x18\x01 \x02(\t\x12\x0e\n\x06sender\x18\x02 \x02(\t')
)




_SECUREMESSAGE = _descriptor.Descriptor(
  name='SecureMessage',
  full_name='serializer.SecureMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='serializer.SecureMessage.body', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sender', full_name='serializer.SecureMessage.sender', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['SecureMessage'] = _SECUREMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SecureMessage = _reflection.GeneratedProtocolMessageType('SecureMessage', (_message.Message,), dict(
  DESCRIPTOR = _SECUREMESSAGE,
  __module__ = 'secure_message_pb2'
  # @@protoc_insertion_point(class_scope:serializer.SecureMessage)
  ))
_sym_db.RegisterMessage(SecureMessage)


# @@protoc_insertion_point(module_scope)
